### ISSUE TITLE
Slurp forward shortcut conflicts with macos

### ISSUE THREAD

**Issue by den1k** [nextjournal/clojure-mode#11]
![image](https://user-images.githubusercontent.com/4651810/103016891-cca39d00-4510-11eb-9049-a176d5df837f.png)
![image](https://user-images.githubusercontent.com/4651810/103016895-ce6d6080-4510-11eb-8bba-60fb45877cab.png)

**Comment by Heliosmaster** [comment]
@den1k the shortcut is pretty standard though, and Emacs does the same. I'm not sure we should change this.

**Comment by den1k** [comment]
It's your call. However, I'm not sure how valuable that parity is with emacs when the shortcut shifts you into another [macos space](https://support.apple.com/en-us/HT204100) and the only way around it is to either close all other spaces or open preferences and disable the default shortcut. That's a lot to ask of users to make a shortcut work. If you can overwrite the OS default, that would be great.

**Comment by mk** [comment]
We also have slurp/barf forward bound to <kbd>Mod</kbd>-<kbd>Shift</kbd>-<kbd>k</kbd>/<kbd>j</kbd>, see:
https://github.com/nextjournal/clojure-mode/blob/3277e2a36d123a34a5613275cde93f0e5557e797/src/main/nextjournal/clojure_mode/keymap.cljs#L122-L139

I'm struggling to find other bindings that work. In maria.cloud it's also bound to <kbd>Cmd</kbd>-<kbd>Shift</kbd>-<kbd>ArrowRight</kbd> but that overrides standard selection behavior.

@den1k let me know if you think <kbd>Mod</kbd>-<kbd>Shift</kbd>-<kbd>k</kbd>/<kbd>j</kbd> works.

**Comment by mk** [comment]
@den1k I've added the alternate keybindings to https://nextjournal.github.io/clojure-mode/. Please reopen if you think we should still add more alternatives for this.

**Comment by den1k** [comment]
@mk Mod-Shift-k/j works!
