### ISSUE TITLE
nextjournal.clojure-mode is not a qualified symbol

### ISSUE THREAD

**Issue by souenzzo** [nextjournal/clojure-mode#16]
The library behind `clojure` cli, `org.clojure/tools.deps.alpha` in the version `0.9.745` released on `July 22, 2020` add this behavior:

- Deprecated use of unqualified lib names in deps.edn - will continue to work but will generate warnings

https://github.com/clojure/tools.deps.alpha/blob/master/CHANGELOG.md

In the demo website of this library:

https://nextjournal.github.io/clojure-mode/

https://github.com/nextjournal/clojure-mode/blob/gh-pages/index.html#L203

It still recommend the usage of unqualified sym.

The current behavior, will expand `nextjournal.clojure-mode` into `nextjournal.clojure-mode/nextjournal.clojure-mode`

But I think that will be nicer use a sorter name like: `nextjournal/clojure-mode`

**Comment by mk** [comment]
Hi @souenzzo,

Thanks for catching that, `nextjournal/clojure-mode` is indeed what we will call the artifact once released and in https://github.com/nextjournal/clojure-mode-demo/blob/a1535932b046aa4cae955e918b9b45a4356eeae2/deps.edn#L1 we used this name. It's just wrong on the demo page. Fix incoming.

**Comment by mk** [comment]
Fixed in ba97fd36923a68be864dc7d3140b6b03668c8e8d.
