### ISSUE TITLE
standard cljs support?

### ISSUE THREAD

**Issue by raymcdermott** [nextjournal/clojure-mode#17]
It seems like `shadow-cljs` is a must for the project as it stands.

Are there plans to remove that dependency?

My selfish interest is because if I need to adopt shadow, I'll go towards it for one of my projects. 

Otherwise I'll stick with figwheel-main.

**Comment by mk** [comment]
Hey @raymcdermott!

Shadow should not be a hard requirement but we did run into an issue with npm-deps with stock ClojureScript: https://clojure.atlassian.net/browse/CLJS-3293. I'll try again with the recent ClojureScript release.

Did you run into a particular issue? I guess our use of shadow.resource in https://github.com/nextjournal/clojure-mode/blob/a42fd57b81b7411cef16059fbbe5de0c66d70728/src/nextjournal/clojure_mode/live_grammar.cljs#L9 might be problematic but that's only meant to be a dev affordance and we can look into separating it more cleanly.

Can't promise I'll get around to it this week still but I'll try.

**Comment by raymcdermott** [comment]
My issue is indeed with npm dependencies.

For my own part, I'm going to start a new project with shadow to use the mode.

**Comment by raymcdermott** [comment]
And @mk thank you so much for this excellent work!!
