### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by Bardia95** [nextjournal/clojure-mode#27]
is there a way I can include this inside a js project as a npm package?

**Comment by marijnh** [comment]
On closer look, https://www.npmjs.com/package/clojure-mode exists, but appears to be published by [someone](https://github.com/victorb) not affiliated with nextjournal?

**Comment by borkdude** [comment]
You can now use this package from NPM:

https://npmjs.com/package/@nextjournal/clojure-mode

In fact, you can even use it directly from a CDN using import-maps now, as demonstrated in this HTML file:

https://squint-cljs.github.io/squint/

More docs around this will be added soon (cc @zampino )

**Comment by borkdude** [comment]
Here you go: https://github.com/nextjournal/clojure-mode#use-it-from-npm

@zampino @mk I guess we can close this issue now
