### ISSUE TITLE
How do I include this? Readme instructions need updating

### ISSUE THREAD

**Issue by interstar** [nextjournal/clojure-mode#35]
Just followed your instructions on the Readme page and I get

    Error building classpath. Library nextjournal.clojure-mode/nextjournal.clojure-mode has prefix sha, use full sha or add tag

**Comment by mk** [comment]
Hi @interstar, I've updated the coordinates to use the tools.deps ability to infer the `:git/url` and changed `:sha` to `:git/sha`:

```sh
clj -Sdeps '{:deps {io.github.nextjournal/clojure-mode {:git/sha "1f55406087814a0dda6806396aa596dbe13ea302"}}}'
```

**Comment by interstar** [comment]
Thanks.

I realise my problem was I was trying to use the shortened version of the SHA that is published on the GitHub front-page rather than the full version.
